
####################################################################
####################################################################
########################### AUTH REQUESTS ##########################
####################################################################
####################################################################

### Singup Request
POST http://localhost:5000/auth/singUp
Content-Type: application/json

{
  "firstName": "Ayham",
  "lastName": "Alhettini",
  "email": "ayham.hittini268@gmail.com",
  "password": "Pa$$w0rd"
}

### Login Request
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "ayham.hittini268@gmail.com",
  "password": "Pa$$w0rd"
}

### Logout Request
DELETE http://localhost:5000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE1OTI5NzIsImV4cCI6MTcyMTU5MzU3Mn0.iQ1uO2RxyHI95ScgfU1OdyHQ9HRJo4I2BB66b-s-D6A
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE1OTI3ODYsImV4cCI6MTcyMjQ1Njc4Nn0.Qn_wPFiV_8U_jqgRAQcKnYwZvQHmviuwhBqSBKvvRxo"
}

### Generate Access Token Request
POST http://localhost:5000/auth/generateAccessToken
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE1OTMwMDEsImV4cCI6MTcyMjQ1NzAwMX0.sfS2ztgpVJDJdGx30cFE31DUgX50MhuW-szBc-L8R24"
}

####################################################################
####################################################################
########################### TASK REQUESTS ##########################
####################################################################
####################################################################

### Create Task Request
POST http://localhost:5000/task/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE2NTQ5MjMsImV4cCI6MTcyMTY1NTUyM30.K7YSaqHxgVBUB99NSUDrMvgATpiBXnUV3w0v59YBjpY
Content-Type: application/json

{
  "taskTitle": "Task3",
  "taskDescription": "Task3 descirption ...."
}

### Get Tasks Request
GET http://localhost:5000/task/get?taskPriority=Regular
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE2NTQ5MjMsImV4cCI6MTcyMTY1NTUyM30.K7YSaqHxgVBUB99NSUDrMvgATpiBXnUV3w0v59YBjpY


### Update Task
PATCH http://localhost:5000/task/update/669d6d0d29a691b1464e46d2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE2NTc0MjIsImV4cCI6MTcyMTY1ODAyMn0.6dhpDx5XlvmqMQ9OaNVL0U5xsrT2T6RilCa9HG5RXJA
Content-Type: application/json

{
  "isTaskCompleted": true,
  "taskDueDate": "2024-07-23",
  "taskPriority": "High"
}

### Delete Task
DELETE http://localhost:5000/task/delete/669d6cce29a691b1464e46d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE1OTMwMTksImV4cCI6MTcyMTU5MzYxOX0.545UcCWrtkRjw-90pEODWgd1HqK-gIW5ecZ-KhiT-hU

