
####################################################################
####################################################################
########################### AUTH REQUESTS ##########################
####################################################################
####################################################################

### Singup Request
POST http://localhost:5000/auth/singUp
Content-Type: application/json

{
  "firstName": "Ayham",
  "lastName": "Alhettini",
  "email": "ayham.hittini268@gmail.com",
  "password": "Pa$$w0rd"
}

### Login Request
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "ayham.hittini268@gmail.com",
  "password": "Pa$$w0rd"
}

### Logout Request
DELETE http://localhost:5000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE1OTI5NzIsImV4cCI6MTcyMTU5MzU3Mn0.iQ1uO2RxyHI95ScgfU1OdyHQ9HRJo4I2BB66b-s-D6A
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlkNmJiMzI5YTY5MWIxNDY0ZTQ2YmMiLCJpYXQiOjE3MjE1OTI3ODYsImV4cCI6MTcyMjQ1Njc4Nn0.Qn_wPFiV_8U_jqgRAQcKnYwZvQHmviuwhBqSBKvvRxo"
}

### Generate Access Token Request
POST http://localhost:5000/auth/generateAccessToken
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFlNmQ2NjFjNGQ4YWFkYjIwYWNmOWYiLCJpYXQiOjE3MjI3MDczMDUsImV4cCI6MTcyMzU3MTMwNX0.JOJRJT-g_ywMmr43ZxJq1HMaaeXwhAbzdv70RN2xaH4"
}

####################################################################
####################################################################
########################### TASK REQUESTS ##########################
####################################################################
####################################################################

### Get Tasks Request
GET http://localhost:5000/task/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFlNmQ2NjFjNGQ4YWFkYjIwYWNmOWYiLCJpYXQiOjE3MjI4MDQ4MDgsImV4cCI6MTcyMjgwNDgzOH0.P2PRReXg3kNxMMcgR2o-pQ7ShlnD1Dh0vJRfc1WGBAo

### Create Task Request
POST http://localhost:5000/task/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFlNmQ2NjFjNGQ4YWFkYjIwYWNmOWYiLCJpYXQiOjE3MjI4MDQ3NzAsImV4cCI6MTcyMjgwNDc4MH0.6K8PK4vktcYdApfzbklSrs0AkXioEEw3_oB54CEUsNU
Content-Type: application/json

{
  "taskTitle": "Task 3"
}

### Update Task
PATCH http://localhost:5000/task/update/66ae8dd0040d3eb8b8a3b7d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFlNmQ2NjFjNGQ4YWFkYjIwYWNmOWYiLCJpYXQiOjE3MjI3MTYyMDUsImV4cCI6MTcyMjgwMjYwNX0.xgamv3cPbiqna63tcjV4NGuHmWA9klL8XjU4mIduojw
Content-Type: application/json

{
  "isTaskCompleted": true
}

### Delete Task
DELETE http://localhost:5000/task/delete/669d6cce29a691b1464e46d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFlNmQ2NjFjNGQ4YWFkYjIwYWNmOWYiLCJpYXQiOjE3MjI3MTYyMDUsImV4cCI6MTcyMjgwMjYwNX0.xgamv3cPbiqna63tcjV4NGuHmWA9klL8XjU4mIduojw

